const collectInSet = require("./collectInSet");
const collectInArray = require("./collectInArray");

/**
 * @module async.collect
 */

/**
 * Collect the values generated by `gen` into a given collection or into a new array.
 *
 * Also works with streams.
 *
 * @param {AsyncIterator} gen
 * @param {Set<any>|any[]} [collection]
 * @async
 * @returns {Promise<Set<any>|any[]>}
 */
const collect = async (gen, collection = []) => {
  if (collection instanceof Set) {
    return await collectInSet(gen, collection);
  }
  return await collectInArray(gen, collection);
};

module.exports = collect;
