/**
 * Collect the values generated by `gen` into a new or given array.
 *
 * @param {Generator} gen
 * @param {*[]} array
 * @returns {*[]}
 */
const collectInArray = (gen, array = []) => {
  for (const element of gen) {
    array.push(element);
  }

  return array;
};

module.exports = collectInArray;
