/**
 * Collect the values generated by `gen` into a new or given set.
 *
 * @param {Generator} gen
 * @param {Set<any>} set
 * @returns {Set<any>}
 */
const collectInSet = (gen, set = new Set()) => {
  for (const element of gen) {
    set.add(element);
  }

  return set;
};

module.exports = collectInSet;
